### ISSUE TITLE
Assigning roles to users problem

### ISSUE THREAD

**Issue by jonmixnblend** [yii2mod/yii2-rbac#10]
Hey hey guys.

Just want to say great work on that module. Super easy to set up, and works great so far. I just want to ask what this controller (see attached screenshot) is for? 

![screencapture at mon oct 31 10 23 31 sast 2016](https://cloud.githubusercontent.com/assets/3213781/19848139/20161330-9f54-11e6-8188-ffd1f61b1717.png)

Is there supposed to be functionality in that controller for assigning users to roles, or is that something that I should implement in my user management controller?

I just wanted to check, because, while I can see how to create permissions, roles, etc very quickly, assigning users to those roles is one thing I can't see how to do using this, and I'm just wondering if I'm missing it here, have set something up incorrectly, or it is something I must implement on top of the module.

best
Jon

**Comment by igor-chepurnoi** [comment]
Hi, in your grid missing the `view link` - [assignments grid](http://prntscr.com/d162ff).
This link opens the following page - [roles](http://prntscr.com/d163zi)
On this page you can assign all available roles to user.

**Comment by igor-chepurnoi** [comment]
In your case for user with ID=66 this link looks as rbac/assignment/view?id=66

**Comment by igor-chepurnoi** [comment]
Also if you override the [gridViewColumns property](https://github.com/yii2mod/yii2-rbac/blob/master/controllers/AssignmentController.php#L53) you should add the view link to your array as follows:
```php
return [
    'modules' => [
        'admin' => [
            'class' => 'app\modules\admin\Module',
            'modules' => [
                'rbac' => [
                    'class' => 'yii2mod\rbac\Module',
                    'controllerMap' => [
                        'assignment' => [
                            'class' => 'yii2mod\rbac\controllers\AssignmentController',
                            'gridViewColumns' => [
                                 'id',
                                 'username',
                                 'email', 
                                // you should add this code
                                [
                                      'class' => 'yii\grid\ActionColumn',
                                      'template' => '{view}'
                                ]
                             ]
                        ]
                    ]
                ],
            ]
        ],
    ],
  'components' => [
         'authManager' => [
            'class' => 'yii\rbac\DbManager',
            'defaultRoles' => ['guest', 'user']
        ],
    ]
];
```

**Comment by jonmixnblend** [comment]
Hey hey @igor-chepurnoi Thanks for getting back to me so quickly.

Yeah I see,:) Since the action column never changes (i.e. it's just the view link and no others on that grid, would it not be an idea to ArrayHelper::merge the action column with that gridViewColumns array on setup? That way, if it is left out of the gridViewColumns config array, it will be merged in anyway, and if it is defined, then it can be overridden?

Thanks again for putting together such an easy to use module, and thank you again for getting back to me so quickly. Hope this finds you well.

**Comment by igor-chepurnoi** [comment]
> Since the action column never changes (i.e. it's just the view link and no others on that grid, would it not be an idea to ArrayHelper::merge the action column with that gridViewColumns array on setup? 

Resolved by 3219ffd

**Comment by igor-chepurnoi** [comment]
I create the new release 1.8 with this 3219ffd changes. Update your package by `composer update`.
Thanks.

**Comment by jonmixnblend** [comment]
Thank you so so much:)

**Comment by igor-chepurnoi** [comment]
You are welcome :)
