### ISSUE TITLE
Generating Routes

### ISSUE THREAD

**Issue by deadmantfa** [yii2mod/yii2-rbac#16]
Hi yii2mod team,

Thank you for this extension.

I have a query and was unable to find a solution on my own. I am using your extension in the Yii 2 Advance template, for my backend application.

I do not have modules in my backend and it should just list all the actions from the controllers eg SiteController but it going to my vendor directory and fetching actions from the gridview extension i am using.

Can you guide me how I can configure it to get the correct actions.

Regards,
Wenceslaus Dsilva

**Comment by deadmantfa** [comment]
Also, can you tell me what the routes are used for, like does it create permissions by going to each module controller action

**Comment by igor-chepurnoi** [comment]
How do you configure your app? Can you please show your configuration for rbac here?

**Comment by deadmantfa** [comment]
Here is the configuration for your module
`` 
'modules'=>[
'rbac' => [
            'class' => 'yii2mod\rbac\Module',
//            'as access' => [
//                'class' => AccessControl::className()
//            ],
            // Some controller property maybe need to change.
            'controllerMap' => [
                'assignment' => [
                    'class' => 'yii2mod\rbac\controllers\AssignmentController',
                    'userIdentityClass' => 'common\models\Admin',
                    'searchClass' => [
                        'class' => 'yii2mod\rbac\models\search\AssignmentSearch',
                        'pageSize' => 10,
                    ],
                    'idField' => 'id',
                    'usernameField' => 'username',
                    'gridViewColumns' => [
                        'id',
                        'username',
                        'email'
                    ]
                ],
                'role' => [
                    'class' => 'yii2mod\rbac\controllers\RoleController',
                    'searchClass' => [
                        'class' => 'yii2mod\rbac\models\search\AuthItemSearch',
                        'pageSize' => 10,
                    ],
                ],
                'rule' => [
                    'class' => 'yii2mod\rbac\controllers\RuleController',
                    'searchClass' => [
                        'class' => 'yii2mod\rbac\models\search\BizRuleSearch',
                        'pageSize' => 10
                    ],
                ],
                'route' => [
                    'class' => 'yii2mod\rbac\controllers\RouteController',
                    // for example: exclude `api, debug and gii` modules from list of routes
                    'modelClass' => [
                        'class' => 'yii2mod\rbac\models\RouteModel',
                        'excludeModules' => ['debug', 'gii', 'gridview', 'dynagrid', 'datecontrol'],
                    ],
                ],
            ]
        ],
.....
],
'components'=>[
'authManager' => [
            'class' => 'yii\rbac\DbManager',
            'itemTable' => '{{%admin_auth_item}}',
            'itemChildTable' => '{{%admin_auth_item_child}}',
            'assignmentTable' => '{{%admin_auth_assignment}}',
            'ruleTable' => '{{%admin_auth_rule}}',
            'defaultRoles' => ['guest', 'user', 'admin'],
        ],
'as access' => [
            'class' => yii2mod\rbac\filters\AccessControl::class,
            'allowActions' => [
//            '/rbac/route',
//            '/user/login',
                // The actions listed here will be allowed to everyone including guests.
                // So, 'admin/*' should not appear here in the production, of course.
                // But in the earlier stages of your development, you may probably want to
                // add a lot of actions here until you finally completed setting up rbac,
                // otherwise you may not even take a first step.
            ]
        ],
......
]
``

**Comment by igor-chepurnoi** [comment]
> Also, can you tell me what the routes are used for, like does it create permissions by going to each module controller action

Routes allows you to skip configurations like this
```php
[
    'allow' => true,
    'actions' => ['login', 'signup', 'request-password-reset', 'password-reset'],
    'roles' => ['?'],
],
```
You need to assign routes to permissions and assign permissions to roles. [For example](https://github.com/yii2mod/base/blob/master/rbac/migrations/m160722_085418_init.php)

**Comment by deadmantfa** [comment]
Cool, Cause i was thinking if it can generate the routes for me through the gui then i dont need to write the migrations for the same if that's the case I shall do it the way you suggested

**Comment by igor-chepurnoi** [comment]
Yes, you're right
