### ISSUE TITLE
PHP7 matter: Declaration of rbac\controllers\Role: should be compatible with AuthItemController::actionCreate($type)

### ISSUE THREAD

**Issue by markopetelin** [yii2mod/yii2-rbac#18]
### What steps will reproduce the problem?
use PHP 7

### What is the expected result?
access to /rbac/role/index form
### What do you get instead?
http://prntscr.com/g4bsuw
### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      | Yii v2.0.12
| Yii2-rbac version |dev-master c7c7685 => 2.0
| PHP version       | PHP 7.0.21-1~ubuntu14.04.1+deb.sury.org+1

**Comment by igor-chepurnoi** [comment]
You need to remove $item from you RoleController class

**Comment by markopetelin** [comment]
solved, thanks!



and then used %$item in actionCreate
