### ISSUE TITLE
Ldap Integration

### ISSUE THREAD

**Issue by joralemarti** [yii2mod/yii2-rbac#19]
Hi, 
I would like to implement this extension on a project that I need to integrate with ldap authentication and ldap group mapping with roles. Any advice to achive this?

**Comment by igor-chepurnoi** [comment]
Hi, 
I think you need to create custom component for communicate with ldap db, and maybe some component for retrieving roles and groups into your system.

**Comment by igor-chepurnoi** [comment]
I don't have any expirience with ldap service

**Comment by igor-chepurnoi** [comment]
Maybe you can try the following packages
- https://github.com/andrey-tm/yii2-ldap-auth-module
- https://github.com/chrmorandi/yii2-ldap
