### ISSUE TITLE
Require PHP 7.1?

### ISSUE THREAD

**Issue by thiagotalma** [yii2mod/yii2-rbac#20]
Are you using any PHP 7.1 functionality?

If you are not using any, there is no need to require PHP 7.1.

And if you are using it, it would be nice to try to solve it in a way that PHP 7.1 is not required.

Stable versions of the most commonly used distributions are in PHP 7.0.
If you require PHP 7.1 a lot of people will be required to stop using this extension.

**Comment by igor-chepurnoi** [comment]
I think it's not a problem if you want you can always install the previous version of the package. Many of packages already require php 7.1, [for example](https://github.com/symfony/event-dispatcher/)

**Comment by thiagotalma** [comment]
You are right to be inspired by the great packages.

But let's study how they do the work:

![](http://i.imgur.com/Mo3KJqW.png)

![](http://i.imgur.com/7vPCnFq.png)

![](http://i.imgur.com/sQJOpxC.png)

![](http://i.imgur.com/421vzgH.png)

See that they have a lot of work making modifications and improvements in several versions, but always maintaining compatibility.

Small extensions like yours and mine also have this option to keep multiple versions, but we know that this is not feasible.

So the best option would be to ensure that most people can use our extensions, either by following the yii2 requirement or at most the stable version of the most common distros (debian, ubuntu, centos, etc ...).

**Comment by igor-chepurnoi** [comment]
Ok, I understand. I'll update php version to 7.0 later

**Comment by thiagotalma** [comment]
That's it!
Good job

**Comment by thiagotalma** [comment]
@igor-chepurnoi You can take the opportunity to release a version  ;-)

**Comment by igor-chepurnoi** [comment]
Of course, thanks)

**Comment by thiagotalma** [comment]
Hello @igor-chepurnoi 
Do you have an estimate when you can release the new version?

**Comment by igor-chepurnoi** [comment]
Hi, @thiagotalma 
I will do it today.

**Comment by IvoPereira** [comment]
Hello @igor-chepurnoi!

Have you ever concluded this issue?

I've encountered this again today when requiring the package:

```
Resolving dependencies through SAT
Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - zendframework/zend-code 3.3.0 requires php ^7.1 -> your PHP version (7.0.14) does not satisfy that requirement.
    - zendframework/zend-code 3.3.0 requires php ^7.1 -> your PHP version (7.0.14) does not satisfy that requirement.
    - Installation request for zendframework/zend-code (locked at 3.3.0) -> satisfiable by zendframework/zend-code[3.3.0].


Installation failed, reverting ./composer.json to its original content.
```
