### ISSUE TITLE
Update RouteModel.php to future proof for php 7.2

### ISSUE THREAD

**Issue by sinfuljosh** [yii2mod/yii2-rbac#23]
Since you are pushing forward using the most recent versions of php. 

You should update the [RouteModel.php](https://github.com/yii2mod/yii2-rbac/blob/master/models/RouteModel.php) and change `yii\base\Object` to `yii\base\BaseObject`.  

Also need to change the `extends Object` to `extends BaseObject`.  

This is mentioned in [Yii2 upgrade notes](https://github.com/yiisoft/yii2/blob/2.0.13/framework/UPGRADE.md#upgrade-from-yii-2012) and I encountered the issue when performing a clean install of [yii2mod/base](https://github.com/yii2mod/base). 

I was using a newer version of laragon and it comes with php 7.2 or else I never would have caught this. 

I am also curious if this is related to other problems people have reported in relation to the route access control.

**Comment by igor-chepurnoi** [comment]
Hi, thanks for the issue. I will try to fix these problems on this week.

**Comment by igor-chepurnoi** [comment]
Fixed by #24
