### ISSUE TITLE
Do create role and permission function actually work?

### ISSUE THREAD

**Issue by umbalaconmeogia** [yii2mod/yii2-rbac#25]
When I use the UI screen `rbac/permission/create` or `rbac/role/create` to create new one, it throw errors as below.

> Missing argument 1 for yii2mod\rbac\models\AuthItemModel::find(), called in ...\vendor\yiisoft\yii2\validators\UniqueValidator.php on line 210 and defined

This is because in UniqueValidator, it call the ActiveRecord::find() (as all of us get familiar),
but the class yii2mod\rbac\models\AuthItemModel itself redefines the find($id) function.
```php
    public static function find($id)
    {
        //...
    }
```

So I wonder whether there is anyone can use these UI functions to create/update Role and Permission.
![yii2modrbac error](https://user-images.githubusercontent.com/179130/34986546-55f3d312-fafb-11e7-8cf3-7e550a8bd2ab.png)

**Comment by igor-chepurnoi** [comment]
Hi, I fixed this issue, can you update this package to 2.3 version?

**Comment by umbalaconmeogia** [comment]
Thank you. It seems that I've got version 2.0 because I'm using PHP 5.6 :(

**Comment by igor-chepurnoi** [comment]
Yes, the last versions require php >= >=7.0.0

**Comment by umbalaconmeogia** [comment]
OK. Thanks.
