### ISSUE TITLE
How to get a list of standard routes(not modules)

### ISSUE THREAD

**Issue by serjlaw** [yii2mod/yii2-rbac#26]
Hey. Thank you very much for your extension.
I got the routes of the installed modules in http://localhost/path/to/index.php?r=rbac/route. BUT how do I get routes for my action in my controllers (SiteController and other)?

**Comment by igor-chepurnoi** [comment]
Hi, this module doesn't provide any components for getting routes by specific controller name.

**Comment by igor-chepurnoi** [comment]
You only can view routes in the admin panel.

**Comment by serjlaw** [comment]
How do I control access to "user / index" or to the root of the site (http: // localhost /)? How do I add these routs?

**Comment by igor-chepurnoi** [comment]
I will try to describe the whole process later, maybe tonight.

**Comment by igor-chepurnoi** [comment]
1. You need to create role, for example "manager"
2. You need to create permission, for example "manage users" and assign
3.

**Comment by serjlaw** [comment]
Fine! Thank you. I will look forward to it.

**Comment by serjlaw** [comment]
I think I found what I was looking for. Is this "https://github.com/mdmsoft/yii2-admin/" your fork?

**Comment by igor-chepurnoi** [comment]
yep

**Comment by serjlaw** [comment]
Ok. I think the idea with the addition of a route in admin panel is good. Thanks for the help.
