### ISSUE TITLE
table not found

### ISSUE THREAD

**Issue by mindochin** [yii2mod/yii2-rbac#5]
Base table or view not found: 1146 Table 'lrf.auth_item_child' doesn't exist
The SQL being executed was: SELECT * FROM `auth_item_child`

в базу таблицы записались как AuthItemChild

**Comment by igor-chepurnoi** [comment]
Hi, change configuration for `authManager` in the application config, for example:
```php
'authManager' => [
            'class' => 'yii\rbac\DbManager',
            'defaultRoles' => ['guest', 'user'],
            'itemTable' => 'AuthItem',
            'itemChildTable' => 'AuthItemChild',
            'assignmentTable' => 'AuthAssignment',
            'ruleTable' => 'AuthRule',
        ],
```
