### ISSUE TITLE
RBAC doesn't apply to /rbac route

### ISSUE THREAD

**Issue by jeredfloyd** [yii2mod/yii2-rbac#7]
RBAC rules don't appear to apply to the /rbac route.  This means that any user with an account can access /rbac and modify their rights.  Am I missing something?

**Comment by igor-chepurnoi** [comment]
Hi, basically you need to create the following roles: admin, user, guest. After creating the roles, you need to create the permissions with routes, for example: permission name - adminManagement with route /admin/*, and assign this permission to the admin role. And then assign the admin role to the user.

Complete example with the admin panel, user management and rbac you can find here: [yii2mod/base](https://github.com/yii2mod/base).
> Also you can see the basic insert migration (with predefined roles: admin, user, guest) for the rbac here: [rbac migration](https://github.com/yii2mod/base/blob/master/migrations/m130524_201442_init.php#L208)

**Comment by jeredfloyd** [comment]
I see; we weren't using the admin panel and instead the rbac controller directly, which was not access controlled.  Thanks.

**Comment by neoacevedo** [comment]
https://github.com/yii2mod/yii2-rbac/issues/7#issuecomment-212821875
How to do it?
