### ISSUE TITLE
Access controle to RBAC module

### ISSUE THREAD

**Issue by ilyatau** [yii2mod/yii2-rbac#8]
Hello,
I can control access to all my controllers with you rbac module.
But I can't close access to rbac module it self.
Or I don't understand something.
Thanks

**Comment by igor-chepurnoi** [comment]
Hi, you can add rbac module to the [admin module](https://github.com/yii2mod/base/blob/master/config/main.php#L13). And then only the users that have access rights to the admin panel of the website will be able to have access to the rbac module.

You can install our [base template](https://github.com/yii2mod/base). In this template only user with admin role has access to the rbac module.

**Comment by ilyatau** [comment]
I am using advanced template. And try use rbac module in backend app.

**Comment by ilyatau** [comment]
I found way for solution.
You can add to config this code
```php
'modules' => [
      ......
        'rbac' => [
            'class' => 'yii2mod\rbac\Module',
            'as access' => [
                'class' => yii2mod\rbac\components\AccessControl::className()
            ],
            //Some controller property maybe need to change. 
           'controllerMap' => [
                        'assignment' => [
                            'class' => 'yii2mod\rbac\controllers\AssignmentController',
                            'userClassName' => 'path\to\models\User',
                        ]
                    ]
        ],
    ]
```
Please add this example to you readme file. Maybe it will help to other users.

**Comment by igor-chepurnoi** [comment]
ok, thanks
